# Made to work on khadas vim4
FROM arm64v8/node:18-bullseye

WORKDIR /app

COPY . ./

RUN npm install

RUN npx prisma generate

RUN npx prisma migrate dev --name init

RUN npm run build

CMD ["npm", "run", "start"]